### ISSUE TITLE
Upload  a preview.

### ISSUE THREAD

**Issue by iSaulX** [OgaDavid/sneakers-head-frontend#1]
Everyone here wanna how your project look without deploy anything before.
I suggest to upload a image preview to `README.md` to show us how the project look, or upload it to a demo app, hoster on a free hoster (Vercel, netlify, github pages, etc)

Thank you.

**Comment by OgaDavid** [comment]
The app Is deployed to vercel (nike-shop-two.vercel.app)... You can check the description tab on the repo for the link too. Thanks for the advice, I'll update the readme soon!
